version: '3.8'

services:
  red-comunitaria-app:
    build: ./backend-node  # <-- Apuntamos a la carpeta donde está el Dockerfile
    container_name: servicio-b-viajes
    restart: always
    ports:
      - "3001:3001"        # <-- Puerto PC : Puerto Contenedor (Deben coincidir)
    environment:
      - PORT=3001          # <-- Node escuchará en 3001 dentro del contenedor